apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml

helmCharts:
- name: pg-db
  releaseName: ${ARGOCD_ENV_gitlab_app_name}
  version: ${ARGOCD_ENV_pgdb_helm_version}
  repo: https://percona.github.io/percona-helm-charts/
  valuesFile: gitlab-db-values.yaml
  namespace: ${ARGOCD_ENV_gitlab_namespace}

- name: pg-db
  releaseName: gitaly
  version: ${ARGOCD_ENV_pgdb_helm_version}
  repo: https://percona.github.io/percona-helm-charts/
  valuesFile: gitaly-db-values.yaml
  namespace: ${ARGOCD_ENV_gitlab_namespace}  