apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: git-lfs
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  bucketName: git-lfs
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000"
    maxSize: "2G"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-artifacts
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  bucketName: gitlab-artifacts
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000"
    maxSize: "2G"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-uploads
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  bucketName: gitlab-uploads
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000"
    maxSize: "2G"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-packages
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  bucketName: gitlab-packages
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000"
    maxSize: "2G"
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-sercret-creator
  namespace: ${ARGOCD_ENV_gitlab_namespace}      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${ARGOCD_ENV_gitlab_namespace}
  name: gitlab-secret-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-sercret-creator
  namespace: ${ARGOCD_ENV_gitlab_namespace}
subjects:
  - kind: ServiceAccount
    name: gitlab-secret-creator
roleRef:
  kind: Role
  name: gitlab-secret-role
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-k8s-secret-store
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: "gitlab-sercret-creator"
          namespace: ${ARGOCD_ENV_gitlab_namespace}
      remoteNamespace: ${ARGOCD_ENV_gitlab_namespace} 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-rails-secret-lfs
  namespace: ${ARGOCD_ENV_gitlab_namespace}
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: SecretStore
    name: gitlab-k8s-secret-store
  
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: gitlab-lfs
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: gitlab-lfs
      property: AWS_SECRET_ACCESS_KEY

  target:
    name: gitlab-rails-secret-lfs
    creationPolicy: Owner
    template:
      data:
        inventory: |
             s3:
              v4auth: true
              regionendpoint: "http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc"
              pathstyle: true
              region: us-east-1
              accesskey: {{.AWS_ACCESS_KEY_ID}}
              secretkey: {{.AWS_SECRET_ACCESS_KEY}}