apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: redis-password-policy
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  # Add fields here
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  passwordPolicy: |
    length = 20
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }
      rule "charset" {
        charset = "_"
        min-chars = 1
      }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: redis-password
  namespace: ${ARGOCD_ENV_vault_namespace} 
spec:
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: /secret/data/redis
  secretKey: password
  secretFormat:
    passwordPolicyName: redis-password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: gitlab-redis-secret
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  refreshPeriod: 1m0s
  vaultSecretDefinitions:
    - authentication:
        path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
        role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
        serviceAccount:
          name: default
      name: dynamicsecret_redis_password
      path: /secret/data/redis/redis-password
  output:
    name: gitlab-redis-secret
    stringData:
      redis-password: '{{ .dynamicsecret_redis_password.password }}'
    type: Opaque
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "${ARGOCD_ENV_gitlab_namespace}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "${ARGOCD_ENV_gitlab_namespace}"