apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  namespace: ${ARGOCD_ENV_zitadel_namespace}
  name: ${ARGOCD_ENV_argocd_oidc_secret}
spec:
  refreshInterval: 30s
  secretStoreRefs:
    - name: k8s-store-zitadel-to-argocd
      kind: SecretStore
  selector:
    secret:
      name: ${ARGOCD_ENV_argocd_oidc_secret}

  template:
    engineVersion: v2
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
  data:
    - match:
        remoteRef:
          remoteKey: ${ARGOCD_ENV_argocd_oidc_secret}
