apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: ${ARGOCD_ENV_argocd_namespace}
  name: ${ARGOCD_ENV_argocd_oidc_secret}
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: SecretStore
    name: k8s-store-zitadel
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        oidc_client_id: "{{ .oidc_client_id | toString }}"
        oidc_client_secret: "{{ .oidc_client_id | oidc_client_secret }}"
    name: ${ARGOCD_ENV_argocd_oidc_secret}
    creationPolicy: Owner
  data:
    - secretKey: oidc_client_id
      remoteRef:
        key: ${ARGOCD_ENV_argocd_oidc_secret}
        property: oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: ${ARGOCD_ENV_argocd_oidc_secret}
        property: oidc_client_secret
