apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: masterkey-generator
  namespace: "${ARGOCD_ENV_zitadel_namespace}"
spec:
  length: 32
  symbols: 0
  noUpper: true
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-masterkey
  namespace: "${ARGOCD_ENV_zitadel_namespace}"
spec:
  refreshInterval: 0s
  target:
    name: masterkey
    template:
      data:
        masterkey: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: masterkey-generator