apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - env-onboard-xplane-terraform.yaml

secretGenerator:
  - name: terraformrc
    files:
      - .terraformrc=.terraformrc.yaml
    options:
      disableNameSuffixHash: true
