apiVersion: infitx.org/v1alpha1
{{- if contains .Values.engine "aurora" }}
kind: RDSAuroraDBInstanceClaim
{{- else }}
kind: RDSDBInstanceClaim
{{- end }}
metadata:
  name: {{ printf "%s-%s" .Values.namePrefix  .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    organization: Infitx
    author: devops
spec:
  id: {{ printf "%s-%s" .Values.namePrefix  .Values.name }}
  compositionSelector:
    matchLabels:
      provider: aws
  {{- if contains .Values.engine "aurora" }}
      db: rds-aurora
  {{- else }}
      db: rds
  {{- end }}
      cluster: {{ .Values.namePrefix }}
  parameters:
    region: {{ .Values.region }}
    engine: {{ .Values.engine }}
    engineVersion: "{{ .Values.engineVersion }}"
    dbClusterInstanceClass: {{ .Values.dbClusterInstanceClass }}
    vpcId: {{ .Values.vpcId }}
    vpcCidr:  {{ .Values.vpcCidr }}
    {{- with ( splitList "," .Values.subnets) }}
    subnets:  
        {{- toYaml . | nindent 8 }}
    {{- end }}
    dbName: {{ .Values.dbName }}
    username: {{ .Values.userName }}
    passwordSecret:
      key: {{ .Values.passwordSecret.key }}
      name: {{ .Values.passwordSecret.name }}
    allowMajorVersionUpgrade: {{ .Values.allowMajorVersionUpgrade }}
    autoMinorVersionUpgrade: {{ .Values.autoMinorVersionUpgrade }}
    applyImmediately: {{ .Values.applyImmediately }}
    backupRetentionPeriod: {{ .Values.backupRetentionPeriod }}
    preferredBackupWindow: {{ .Values.preferredBackupWindow }}
{{- if not ( contains .Values.engine "aurora" )  }}    
    storageGB: {{ .Values.storageGB }}
    storageType: {{ .Values.storageType }}
    storageIops: {{ .Values.storageIops }}
{{- end }}    
    storageEncrypted: {{ .Values.storageEncrypted }}
