apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name:  ${ARGOCD_ENV_sc_kubernetes_provider_name}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: ${ARGOCD_ENV_capi_cluster_namespace}
      name: ${ARGOCD_ENV_capi_cluster_name}-kubeconfig
      key: value