apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: gitlabdb-password-policy
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  # Add fields here
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  passwordPolicy: |
    length = 20
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }
      rule "charset" {
        charset = "_"
        min-chars = 1
      }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: gitlabdb-password
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: /secret/data/gitlabdb
  secretKey: password
  secretFormat:
    passwordPolicyName: gitlabdb-password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: gitlab-gitlabdb-secret
  namespace: ${ARGOCD_ENV_vault_namespace}
spec:
  refreshPeriod: 1m0s
  vaultSecretDefinitions:
    - authentication:
        path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
        role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
        serviceAccount:
          name: default
      name: dynamicsecret_gitlabdb_password
      path: /secret/data/gitlabdb/gitlabdb-password
  output:
    name: gitlab-postgresql-credentials
    stringData:
      password: "{{ .dynamicsecret_gitlabdb_password.password }}"
    type: Opaque
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "${ARGOCD_ENV_gitlab_namespace}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "${ARGOCD_ENV_gitlab_namespace}"

---
apiVersion: infitx.org/v1alpha1
kind: DBInstanceClaim
metadata:
  name: gitlabdb
  namespace: "${ARGOCD_ENV_gitlab_namespace}"
  annotations:
    organization: Infitx
    author: devops
spec:
  id: gitlabdb
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    region: ${ARGOCD_ENV_cloud_region}
    engineVersion: "16"
    size: small
    storageGB: ${ARGOCD_ENV_rds_postgres_storage_size}
    subnets:  "[${ARGOCD_ENV_rds_subnet_list}]"
    databaseName: gitlab
    userName: gitlab
    masterUserPasswordSecret:
      key: password
      name: gitlab-postgresql-credentials