apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../helmcharts

helmCharts:
  - name: dbmr
    releaseName: gitlabdb
    version: 0.1.0
    valuesFile: gitlab-db-values.yaml
    namespace: ${ARGOCD_ENV_gitlab_namespace}

  - name: dbmr
    releaseName: praefectdb
    version: 0.1.0
    valuesFile: praefect-db-values.yaml
    namespace: ${ARGOCD_ENV_gitlab_namespace}

resources:
  - gitlab-db-secrets.yaml
  - praefect-db-secrets.yaml
