apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - crossplane-providers.yaml
  - crossplane-packages.yaml
  - crossplane-functions.yaml
#  - rook-ceph-objectstore-exporter.yaml

secretGenerator:
  - name: terraformrc
    namespace: ${ARGOCD_ENV_argocd_namespace}
    files:
      - .terraformrc=.terraformrc.yaml
    options:
      disableNameSuffixHash: true
