apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: nexus-password-policy
  namespace: ${ARGOCD_ENV_nexus_namespace}
spec:
  # Add fields here
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  passwordPolicy: |
    length = 20
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }
      rule "charset" {
        charset = "_"
        min-chars = 1
      }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: nexus-password
  namespace: ${ARGOCD_ENV_nexus_namespace} 
spec:
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  isKVSecretsEngineV2: false
  path: /secret/generated/nexus
  secretKey: password
  secretFormat:
    passwordPolicyName: nexus-password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: nexus-secret
  namespace: ${ARGOCD_ENV_nexus_namespace}
spec:
  refreshPeriod: 1m0s
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: policy-admin
        serviceAccount:
          name: default
      name: dynamicsecret_nexus_password
      path: /secret/generated/nexus/nexus-password
  output:
    name: nexus-secret
    stringData:
      nexus-password: '{{ .dynamicsecret_nexus_password.password }}'
    type: Opaque