apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # utils
  - ../../../base/argocd-helm.yaml
  - ../../../base/rook-ceph.yaml
  - ../../../base/external-secrets.yaml
  - ../../../base/reflector.yaml
  - ../../../base/reloader.yaml
  - ../../../base/crossplane.yaml
  - ../../../base/kubernetes-secret-generator.yaml
  - ../../../base/utils-post-config.yaml
  - ../../../base/istio.yaml
  - ../../../base/istio-gw.yaml
  - ../../../base/cert-manager.yaml
  - ../../../base/consul.yaml
  # vault
  - ../../../base/vault.yaml
  - ../../../base/vault-post-config.yaml
  # dns-utils
  - ../../../base/dns-utils.yaml
  - ../../../base/dns-utils-post-config.yaml
  - ../../../base/dns-utils-pre.yaml
  # security
  - ../../../base/zitadel-pre.yaml
  - ../../../base/zitadel-helm.yaml
  - ../../../base/zitadel-post-config.yaml
  #- ../../../base/netbird.yaml
  # nexus
  - ../../../base/nexus.yaml
  - ../../../base/nexus-pre.yaml
  - ../../../base/nexus-post-config.yaml
