apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: ${ARGOCD_ENV_metallb_namespace}
spec:
  addresses:
    - ${ARGOCD_ENV_metallb_ip_range_begin}-${ARGOCD_ENV_metallb_ip_range_end}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: ${ARGOCD_ENV_metallb_namespace}
