apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-crs.yaml

helmCharts:
  - name: consul
    releaseName: ${consul_app_name}
    version: ${consul_helm_version}
    repo: https://helm.releases.hashicorp.com
    valuesFile: consul-values.yaml
    namespace: ${consul_namespace}

  - name: vault
    releaseName: ${vault_app_name}
    version: ${vault_helm_version}
    repo: https://helm.releases.hashicorp.com
    valuesFile: vault-values.yaml
    namespace: ${vault_namespace}
    valuesInline:
      vault:
        statefulSet:
          annotations:
            argocd.argoproj.io/sync-wave: ${vault_sync_wave}
