apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-crs.yaml

helmCharts:
  - name: consul
    releaseName: ${ARGOCD_ENV_consul_app_name}
    version: 1.4.0
    repo: https://helm.releases.hashicorp.com
    valuesFile: consul-values.yaml
    namespace: ${ARGOCD_ENV_consul_namespace}

  - name: vault
    releaseName: ${ARGOCD_ENV_vault_app_name}
    version: 0.24.0
    repo: https://helm.releases.hashicorp.com
    valuesFile: vault-values.yaml
    namespace: ${ARGOCD_ENV_vault_namespace}
    valuesInline:
      vault:
        statefulSet:
          annotations:
            argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_vault_sync_wave}
