apiVersion: v1
kind: Namespace
metadata:
  name: "${ARGOCD_ENV_vault_namespace}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "${ARGOCD_ENV_vault_namespace}"
  name: vault-secret-all
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-binding
  namespace: "${ARGOCD_ENV_vault_namespace}"
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: "${ARGOCD_ENV_vault_namespace}"
roleRef:
  kind: Role
  name: vault-secret-all
  apiGroup: rbac.authorization.k8s.io
---

