apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- virtualservice.yaml

helmCharts:
- name: gitlab
  releaseName: ${ARGOCD_ENV_gitlab_app_name}
  version: ${ARGOCD_ENV_gitlab_helm_version}
  repo: https://charts.gitlab.io/
  valuesFile: gitlab-values.yaml
  namespace: ${ARGOCD_ENV_gitlab_namespace}