apiVersion: v1
kind: ConfigMap
metadata:
  name: ruby-script
  namespace: ${ARGOCD_ENV_gitlab_namespace}
data:
  maketoken.rb: |
    user = User.where(id: 1).first
    token = user.personal_access_tokens.where(name: 'rootapitoken').first
    if token.nil?
        token = user.personal_access_tokens.create(scopes: [:api], name: 'rootapitoken', expires_at: 10.minutes.from_now)
        token.set_token(ENV["TOKEN_VALUE"])
    elsif token.expire_notification_delivered
        token.delete
        token = user.personal_access_tokens.create(scopes: [:api], name: 'rootapitoken', expires_at: 10.minutes.from_now)
        token.set_token(ENV["TOKEN_VALUE"])
    end
    token.save!
    user.save!
