apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_dns_utils_argocd_app_name}
  namespace: ${ARGOCD_ENV_dns_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_dns_utils_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_dns_utils_app_namespace}

  sources:
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_dns_utils_application_gitrepo_tag}
      path: gitops/applications/base/dns-utils
      plugin:
        name: envsubst
        env:
          - name: "external_dns_helm_version"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_helm_version}"

          - name: "external_dns_namespace"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_namespace}"

          - name: "dns_private_subdomain"
            value: "${ARGOCD_ENV_dns_utils_cr_config_dns_private_subdomain}"

          - name: "dns_public_subdomain"
            value: "${ARGOCD_ENV_dns_utils_cr_config_dns_public_subdomain}"

          - name: "dns_cloud_api_region"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_dns_cloud_api_region}"

          - name: "istio_internal_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_gateway_name}"

          - name: "istio_external_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_gateway_name}"

          - name: "istio_internal_wildcard_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_wildcard_gateway_name}"

          - name: "istio_external_wildcard_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_wildcard_gateway_name}"

          - name: "istio_external_gateway_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_gateway_namespace}"

          - name: "istio_internal_gateway_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_gateway_namespace}"

          - name: "internal_load_balancer_dns"
            value: "${ARGOCD_ENV_dns_utils_cr_config_internal_load_balancer_dns}"

          - name: "external_load_balancer_dns"
            value: "${ARGOCD_ENV_dns_utils_cr_config_external_load_balancer_dns}"

          - name: "ext_dns_cloud_policy"
            value: "${ARGOCD_ENV_dns_utils_cr_config_ext_dns_cloud_policy}"

          - name: "letsencrypt_server"
            value: "${ARGOCD_ENV_dns_utils_cr_config_letsencrypt_server}"

          - name: "letsencrypt_email"
            value: "${ARGOCD_ENV_dns_utils_cr_config_letsencrypt_email}"

          - name: "cert_manager_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_cert_manager_namespace}"

    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_dns_utils_application_gitrepo_tag}
      path: gitops/applications/overlays/${ARGOCD_ENV_cloud_provider}/dns-utils
      plugin:
        name: envsubsthelm
        env:
          - name: "external_dns_helm_version"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_helm_version}"

          - name: "external_dns_namespace"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_helm_version}"

          - name: "dns_private_subdomain"
            value: "${ARGOCD_ENV_dns_utils_cr_config_dns_private_subdomain}"

          - name: "dns_public_subdomain"
            value: "${ARGOCD_ENV_dns_utils_cr_config_dns_public_subdomain}"

          - name: "dns_cloud_api_region"
            value: "${ARGOCD_ENV_dns_utils_ext_dns_dns_cloud_api_region}"

          - name: "istio_internal_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_gateway_name}"

          - name: "istio_external_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_gateway_name}"

          - name: "istio_internal_wildcard_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_wildcard_gateway_name}"

          - name: "istio_external_wildcard_gateway_name"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_wildcard_gateway_name}"

          - name: "istio_external_gateway_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_external_gateway_namespace}"

          - name: "istio_internal_gateway_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_istio_internal_gateway_namespace}"

          - name: "internal_load_balancer_dns"
            value: "${ARGOCD_ENV_dns_utils_cr_config_internal_load_balancer_dns}"

          - name: "external_load_balancer_dns"
            value: "${ARGOCD_ENV_dns_utils_cr_config_external_load_balancer_dns}"

          - name: "ext_dns_cloud_policy"
            value: "${ARGOCD_ENV_dns_utils_cr_config_ext_dns_cloud_policy}"

          - name: "letsencrypt_server"
            value: "${ARGOCD_ENV_dns_utils_cr_config_letsencrypt_server}"

          - name: "letsencrypt_email"
            value: "${ARGOCD_ENV_dns_utils_cr_config_letsencrypt_email}"

          - name: "cert_manager_namespace"
            value: "${ARGOCD_ENV_dns_utils_cr_config_cert_manager_namespace}"
