apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_dns_utils_argocd_app_name}-post-config
  namespace: ${ARGOCD_ENV_dns_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_dns_utils_post_config_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_dns_utils_app_namespace}

  sources:
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_dns_utils_application_gitrepo_tag}
      path: gitops/applications/base/dns-utils-post-config
      plugin:
        name: envsubst
        env:
          - name: "vault_dns_subdomain"
            value: "${ARGOCD_ENV_vault_dns_subdomain}"

          - name: "vault_istio_wildcard_gateway_name"
            value: "${ARGOCD_ENV_vault_istio_wildcard_gateway_name}"

          - name: "vault_istio_gateway_namespace"
            value: "${ARGOCD_ENV_vault_istio_gateway_namespace}"

          - name: "argocd_dns_subdomain"
            value: "${ARGOCD_ENV_argocd_dns_subdomain}"

          - name: "argocd_istio_wildcard_gateway_name"
            value: "${ARGOCD_ENV_argocd_istio_wildcard_gateway_name}"

          - name: "argocd_istio_gateway_namespace"
            value: "${ARGOCD_ENV_argocd_istio_gateway_namespace}"

          - name: "vault_namespace"
            value: "${ARGOCD_ENV_vault_namespace}"

          - name: "argocd_namespace"
            value: "${ARGOCD_ENV_argocd_namespace}"
