apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_gitlab_gitlab_app_name}-pre
  namespace: ${ARGOCD_ENV_gitlab_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_gitlab_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_gitlab_gitlab_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_gitlab_application_gitrepo_tag}
    path: gitops/applications/base/gitlab-pre
    plugin:
      name: envsubst
      env:
        - name: "gitlab_namespace"
          value: "${ARGOCD_ENV_gitlab_gitlab_namespace}"

        - name: "redis_cluster_size"
          value: ${ARGOCD_ENV_gitlab_pre_redis_cluster_size}

        - name: "postgres_replicas"
          value: ${ARGOCD_ENV_gitlab_pre_postgres_replicas}

        - name: "postgres_proxy_replicas"
          value: ${ARGOCD_ENV_gitlab_pre_postgres_proxy_replicas}

        - name: "postgres_storage_size"
          value: ${ARGOCD_ENV_gitlab_pre_postgres_storage_size}
