apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r${ARGOCD_ENV_utils_rook_ceph_app_name}
  namespace: ${ARGOCD_ENV_utils_rook_ceph_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  sources:
    - chart: rook-ceph
      repoURL: https://charts.rook.io/release
      targetRevision: ${ARGOCD_ENV_utils_rook_ceph_helm_version}

      helm:
        releaseName: rook-ceph
        valuesObject:
          csi:
            kubeletDirPath: ${ARGOCD_ENV_utils_rook_ceph_rook_csi_kubelet_dir_path}
          enableDiscoveryDaemon: true

    - chart: rook-ceph-cluster
      repoURL: https://charts.rook.io/release
      targetRevision: ${ARGOCD_ENV_utils_rook_ceph_helm_version}

      helm:
        releaseName: rook-ceph-cluster
