apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${ARGOCD_ENV_utils_storage_private_cloud_provider_post_config_app_name}"
  namespace: ${ARGOCD_ENV_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: "${ARGOCD_ENV_utils_storage_private_cloud_provider_post_config_sync_wave}"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "${ARGOCD_ENV_utils_storage_private_cloud_provider_post_config_namespace}"
  sources:
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_gitlab_application_gitrepo_tag}
      path: gitops/applications/overlays/cloud_provider/private-cloud/block_storage_provider/storage/post-config
      plugin:
        name: envsubst
        env:
          - name: rook_ceph_ext_namespace
            value: "${ARGOCD_ENV_utils_storage_private_cloud_provider_post_config_namespace}"