apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_utils_rook_ceph_app_name}
  namespace: ${ARGOCD_ENV_argocd_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_utils_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_utils_rook_ceph_namespace}
  sources:
    - chart: rook-ceph
      repoURL: https://charts.rook.io/release
      targetRevision: ${ARGOCD_ENV_utils_rook_ceph_helm_version}

      helm:
        releaseName: rook-ceph
        valuesObject:
          csi:
            kubeletDirPath: ${ARGOCD_ENV_utils_rook_ceph_rook_csi_kubelet_dir_path}
          enableDiscoveryDaemon: true

    - chart: rook-ceph-cluster
      repoURL: https://charts.rook.io/release
      targetRevision: ${ARGOCD_ENV_utils_rook_ceph_helm_version}

      helm:
        releaseName: rook-ceph-cluster
