apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_vault_argocd_app_name}
  namespace: ${ARGOCD_ENV_argocd_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_vault_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_argocd_app_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_vault_application_gitrepo_tag}
    path: gitops/applications/base/vault
    plugin:
      name: envsubst
      env:
        - name: "vault_keys_secret"
          value: "${ARGOCD_ENV_vault_vault_vault_keys_secret}"

        - name: "vault_namespace"
          value: "${ARGOCD_ENV_vault_vault_namespace}"

        - name: "consul_storage_size"
          value: "${ARGOCD_ENV_vault_consul_storage_size}"

        - name: "consul_replicas"
          value: "'${ARGOCD_ENV_vault_consul_replicas}'"

        - name: "consul_namespace"
          value: "${ARGOCD_ENV_vault_consul_namespace}"

        - name: "consul_app_name"
          value: "${ARGOCD_ENV_vault_consul_app_name}"

        - name: "consul_helm_version"
          value: "${ARGOCD_ENV_vault_consul_helm_version}"

        - name: "vault_app_name"
          value: "${ARGOCD_ENV_vault_vault_app_name}"

        - name: "vault_helm_version"
          value: "${ARGOCD_ENV_vault_vault_helm_version}"

        - name: "vault_sync_wave"
          value: "${ARGOCD_ENV_vault_vault_sync_wave}"
