apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_security_zitadel_app_name}-pre
  namespace: ${ARGOCD_ENV_security_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_security_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_security_app_namespace}

  sources:
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_security_application_gitrepo_tag}
      path: gitops/applications/base/zitadel-pre
      plugin:
        name: envsubst
        env:
          - name: "zitadel_release_name"
            value: "${ARGOCD_ENV_security_zitadel_app_name}"

          - name: "zitadel_namespace"
            value: "${ARGOCD_ENV_security_zitadel_namespace}"

          - name: "zitadel_helm_version"
            value: "${ARGOCD_ENV_security_zitadel_helm_version}"

          - name: "zitadel_tf_provider_version"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_tf_provider_version}"

          - name: "terraform_modules_tag"
            value: "${ARGOCD_ENV_security_zitadel_terraform_modules_tag}"

          - name: "vault_rbac_admin_group"
            value: "${ARGOCD_ENV_security_zitadel_vault_rbac_admin_group}"

          - name: "zitadel_grant_prefix"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_grant_prefix}"

          - name: "zitadel_istio_gateway_namespace"
            value: "${ARGOCD_ENV_security_zitadel_istio_gateway_namespace}"

          - name: "zitadel_istio_wildcard_gateway_name"
            value: "${ARGOCD_ENV_security_zitadel_istio_wildcard_gateway_name}"

          - name: "zitadel_dns_subdomain"
            value: "${ARGOCD_ENV_security_zitadel_dns_subdomain}"

          - name: "zitadel_post_config_output_secret"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_post_config_output_secret}"

          - name: "argocd_namespace"
            value: "${ARGOCD_ENV_utils_argocd_helm_namespace}"

    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_security_application_gitrepo_tag}
      path: gitops/applications/overlays/rdbms_provider/${ARGOCD_ENV_security_zitadel_rdbms_provider}/zitadel-pre
      plugin:
        name: envsubst
        env:
          - name: "cockroachdb_helm_version"
            value: "${ARGOCD_ENV_security_zitadel_cockroachdb_provider_helm_version}"

          - name: "cockroachdb_pvc_size"
            value: "${ARGOCD_ENV_security_zitadel_cockroachdb_provider_pvc_size}"

          - name: "cockroachdb_release_name"
            value: "${ARGOCD_ENV_security_zitadel_cockroachdb_provider_app_name}"
          
          - name: "zitadel_namespace"
            value: "${ARGOCD_ENV_security_zitadel_namespace}"

          - name: "namespace"
            value: "${ARGOCD_ENV_security_zitadel_namespace}"

          - name: "pgdb_helm_version"
            value: "${ARGOCD_ENV_zitadel_percona_provider_pgdb_helm_version}"                        

          - name: "postgres_replicas"
            value: "${ARGOCD_ENVsecurity_zitadel_percona_provider_postgres_replicas}"

          - name: "postgres_proxy_replicas"
            value: "${ARGOCD_ENV_security_zitadel_percona_provider_proxy_replicas}"

          - name: "postgres_storage_size"
            value: "${ARGOCD_ENV_security_zitadel_percona_provider_postgres_storage_size}"

          - name: "rds_postgres_storage_size"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_postgres_storage_size}"

          - name: "rds_postgres_instance_size"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_postgres_instance_size}"

          - name: "rds_vpc_id"
            value: "${ARGOCD_ENV_zitadel_rds_provider_rdbms_vpc_id}"

          - name: "vpc_cidr"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_vpc_cidr}"

          - name: "rds_subnet_list"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_rdbms_subnet_list}"

          - name: "rds_cloud_region"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_db_provider_cloud_region}"

          - name: "db_secret"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_db_secret}"

          - name: "db_name"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_db_name}"

          - name: "db_username"
            value: "${ARGOCD_ENV_security_zitadel_zitadel_db_username}"

          - name: "dbdeploy_name_prefix"
            value: "${ARGOCD_ENV_security_zitadel_dbdeploy_name_prefix}"

          - name: "db_backup_retention_period"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_backup_retention_period}"

          - name: "db_preferred_backup_window"
            value: "${ARGOCD_ENV__security_zitadel_rds_provider_preferred_backup_window}"

          - name: "db_storage_type"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_db_storage_type}"

          - name: "db_storage_iops"
            value: "${ARGOCD_ENV_security_zitadel_rds_provider_db_storage_iops}"
