apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: netbird
    releaseName: netbird
    namespace: ${ARGOCD_ENV_netbird_namespace}
    version: ${ARGOCD_ENV_netbird_helm_version}
    repo: https://totmicro.github.io/helms
    valuesFile: netbird-values.yaml

  - name: netbird-dashboard
    releaseName: netbird-dashboard
    namespace: ${ARGOCD_ENV_netbird_namespace}
    version: ${ARGOCD_ENV_netbird_dashboard_helm_version}
    repo: https://totmicro.github.io/helms
    valuesFile: netbird-ui-values.yaml

patches:
  - target:
      kind: Service
      name: netbird-management
    patch: |
      - op: add
        path: /spec/ports/0/appProtocol
        value: http2
