apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: netbird
    releaseName: netbird
    namespace: ${ARGOCD_ENV_netbird_namespace}
    # version: ${ARGOCD_ENV_netbird_helm_version}
    version: 1.5.4-rc5
    # repo: https://totmicro.github.io/helms
    repo: https://muzammil360.github.io/totmicro-helms
    valuesFile: netbird-values.yaml

patches:
  - target:
      kind: Service
      name: netbird-management
    patch: |
      - op: add
        path: /spec/ports/0/appProtocol
        value: http2
