apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: ${ARGOCD_ENV_nexus_post_config_app_name}
  namespace: ${ARGOCD_ENV_nexus_namespace}  
spec:
  providerConfigRef:
    name: ${ARGOCD_ENV_nexus_post_config_app_name}
  forProvider:
    roles:
    - "mojaloop.iac.nexus_server"
    varFiles:
    - source: SecretKey
      secretKeyRef:
        namespace: ${ARGOCD_ENV_nexus_namespace}  
        name: nexus-ansible-secret-vars
        key: secret_vars.yaml