apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "${ARGOCD_ENV_netbird_datastore_encryption_key_secret}"
  namespace: "${ARGOCD_ENV_netbird_namespace}"
spec:
  length: 32
  symbols: 0
  noUpper: true
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_netbird_datastore_encryption_key_secret}"
  namespace: "${ARGOCD_ENV_netbird_namespace}"
spec:
  refreshInterval: 0s
  target:
    name: "${ARGOCD_ENV_netbird_datastore_encryption_key_secret}"
    template:
      data:
        "${ARGOCD_ENV_netbird_datastore_encryption_key_secret_key}": "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "${ARGOCD_ENV_netbird_datastore_encryption_key_secret}"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "${ARGOCD_ENV_netbird_relay_secret}"
  namespace: "${ARGOCD_ENV_netbird_namespace}"
spec:
  length: 32
  symbols: 0
  noUpper: true
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_netbird_relay_secret}"
  namespace: "${ARGOCD_ENV_netbird_namespace}"
spec:
  refreshInterval: 0s
  target:
    name: "${ARGOCD_ENV_netbird_relay_secret}"
    template:
      data:
        "${ARGOCD_ENV_netbird_relay_secret_key}": "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "${ARGOCD_ENV_netbird_relay_secret}"