thirdparty-auth-svc-redis:
  enabled: false
  app_owner: "mojaloop"
  resource_type: redis
  deployment_type: helm-chart
  logical_service_config:
    logical_service_port: 6379
    logical_service_name: thirdparty-auth-redis
    username: mojaloop
    user_password_secret: mongodb-reporting-events-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mojaloop    
thirdparty-auth-svc-db:
  enabled: false
  app_owner: "mojaloop"
  resource_type: mysql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 3306
    logical_service_name: thirdparty-auth-db
    username: account_lookup
    user_password_secret: mysql-auth-svc-secret
    user_password_secret_key: mysql-password
    secret_namespaces:
      - mojaloop
    database_name: auth-svc
mysql-consent-oracle-db:
  enabled: false
  app_owner: "mojaloop"
  resource_type: mysql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 3306
    logical_service_name: mysql-consent-oracle
    username: consent-oracle
    user_password_secret: mysql-consent-oracle-secret
    user_password_secret_key: mysql-password
    secret_namespaces:
      - mojaloop
    database_name: consent-oracle
mcm-db:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mysql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 3306
    logical_service_name: mcm-db-svc
    username: devdat1asql1
    user_password_secret: mcm-db-secret
    user_password_secret_key: mysql-password
    secret_namespaces:
      - mcm
    database_name: mcm
account-lookup-db:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mysql
  deployment_type: external
  logical_service_config:
    logical_service_port: 3306
    logical_service_name: account-lookup-db-svc
    username: account_lookup
    user_password_secret: mysql-account-lookup-secret
    user_password_secret_key: mysql-password
    secret_namespaces:
      - mojaloop
    database_name: account_lookup
central-ledger-db:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mysql
  deployment_type: external
  logical_service_config:
    logical_service_port: 3306
    logical_service_name: central-ledger-db-svc
    username: central_ledger
    user_password_secret: mysql-central-ledger-secret
    user_password_secret_key: mysql-password
    secret_namespaces:
      - mojaloop
    database_name: central_ledger
bulk-mongodb:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mongodb
  deployment_type: operator
  logical_service_config:
    logical_service_port: 27017
    logical_service_name: bulk-mongodb-svc
    username: mojaloop
    user_password_secret: mongodb-bulk-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mlos
cep-mongodb:
  enabled: false
  app_owner: "mojaloop"
  resource_type: mongodb
  deployment_type: operator
  logical_service_config:
    logical_service_port: 27017
    logical_service_name: mongodb-cep-mongodb
    username: mojaloop
    user_password_secret: mongodb-cep-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mojaloop
reporting-events-mongodb:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mongodb
  deployment_type: operator
  logical_service_config:
    logical_service_port: 27017
    logical_service_name: mongodb-reporting-events-mongodb
    username: mojaloop
    user_password_secret: mongodb-reporting-events-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mojaloop
mojaloop-kafka:
  enabled: true
  app_owner: "mojaloop"
  resource_type: kafka
  deployment_type: operator
  logical_service_config:
    logical_service_port: 9092
    logical_service_name: mojaloop-kafka-svc
    username: mojaloop
    user_password_secret: mongodb-reporting-events-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mojaloop    
ttk-mongodb:
  enabled: true
  app_owner: "mojaloop"
  resource_type: mongodb
  deployment_type: operator
  logical_service_config:
    logical_service_port: 27017
    logical_service_name: ttk-mongodb-svc
    username: ttk
    user_password_secret: mongodb-ttk-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: ttk
ttk-redis:
  enabled: true
  resource_type: redis
  app_owner: "mojaloop"
  deployment_type: helm-chart
  logical_service_config:
    logical_service_port: 6379
    logical_service_name: ttk-redis
    username: mojaloop
    user_password_secret: mongodb-reporting-events-secret
    user_password_secret_key: mongodb-passwords
    secret_namespaces:
      - mojaloop
    database_name: mojaloop    
keycloak-db:
  enabled: true
  app_owner: "platform"
  resource_type: pgsql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 5432
    logical_service_name: keycloak-db
    username: keycloak
    user_password_secret: pgsql-keycloak-secret
    user_password_secret_key: password
    secret_namespaces:
      - keycloak
    database_name: keycloak
keto-db:
  enabled: true
  app_owner: "platform"
  resource_type: pgsql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 5432
    logical_service_name: keto-db
    username: keto
    user_password_secret: pgsql-keto-secret
    user_password_secret_key: password
    secret_namespaces:
      - ory
    database_name: keto
kratos-db:
  enabled: true
  app_owner: "platform"
  resource_type: pgsql
  deployment_type: operator
  logical_service_config:
    logical_service_port: 5432
    logical_service_name: kratos-db
    username: kratos
    user_password_secret: pgsql-kratos-secret
    user_password_secret_key: password
    secret_namespaces:
      - ory
    database_name: kratos
