apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-dynamic-secrets-dns-config.yaml
  - lets-encrypt-cluster-issuer.yaml

helmCharts:
  - name: external-dns
    releaseName: external-dns
    version: ${ARGOCD_ENV_external_dns_helm_version}
    repo: https://charts.bitnami.com/bitnami
    valuesFile: ext-dns-values.yaml
    namespace: ${ARGOCD_ENV_external_dns_namespace}
    additionalValuesFiles:
      - ext-dns-values.yaml
