apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-crossplane-provider-config
spec:
  credentials:
    secretRef:
      key: creds
      name: secret-aws-xplane-backend-creds
      namespace: ${ARGOCD_ENV_crossplane_namespace}
    source: Secret
  endpoint:
    url:
      dynamic:
        host: amazonaws.com
        protocol: https
      type: Dynamic
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-cp-upbound-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      key: creds
      name: secret-aws-xplane-backend-creds
      namespace: ${ARGOCD_ENV_crossplane_namespace}