apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-postgresql
  labels:
    provider: aws
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: infitx.org/v1alpha1
    kind: DBInstance
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: subnetgroup
        base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: SubnetGroup
          spec:
            forProvider:
              description: Subnet group for DB instance
              region: eu-west-2
              subnetIds: []
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.subnets"
          toFieldPath: "spec.forProvider.subnetIds"
      - name: securityGroup
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroup
          spec:
            forProvider:
              description: Security group for the db instance
              region: eu-west-2
              vpcId: testid
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.vpcId"
          toFieldPath: "spec.forProvider.vpcId"
      - name: securityGroupRule
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroupRule
          spec:
            forProvider:
              description: Db ingress rule
              region: eu-west-2
              type: ingress
              fromPort: 5432
              toPort: 5432
              protocol: tcp
              cidrBlocks:
                - 0.0.0.0/0
              securityGroupIdSelector:
                matchControllerRef: true
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"             
      - name: rdsinstance
        base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: Instance
          spec:
            forProvider:
              region:  eu-west-2
              dbSubnetGroupNameSelector:
                matchControllerRef: true
              vpcSecurityGroupIdSelector:
                matchControllerRef: true
              username: masteruser
              dbName: testdb
              engine: postgres
              skipFinalSnapshot: true
              publiclyAccessible: true
              allocatedStorage: 200
              passwordSecretRef:
                key: password
                name: secretName
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.instanceClass
          transforms:
          - type: map
            map:
              small: db.m5.large
              medium: db.m5.2xlarge
              large: db.m5.8xlarge
        - fromFieldPath: spec.parameters.username
          toFieldPath: spec.forProvider.username
        - fromFieldPath: spec.parameters.dbName
          toFieldPath: spec.forProvider.dbName
        - fromFieldPath: spec.parameters.engineVersion
          toFieldPath: spec.forProvider.engineVersion
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
        - fromFieldPath: spec.parameters.passwordSecret.name
          toFieldPath: spec.forProvider.passwordSecretRef.name
        - fromFieldPath: spec.parameters.passwordSecret.key
          toFieldPath: spec.forProvider.passwordSecretRef.key
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.passwordSecretRef.namespace