apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-postgresql
  labels:
    provider: aws
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: infitx.org/v1alpha1
    kind: DBInstance
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: subnetgroup
        base:
          apiVersion: database.aws.crossplane.io/v1beta1
          kind: DBSubnetGroup
          spec:
            forProvider:
              description: Subnet group for DB instance
              region: eu-west-2
              subnetIds: []
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.subnets"
          toFieldPath: "spec.forProvider.subnetIds"
          
      - name: securityGroup
        base:
          apiVersion: ec2.aws.crossplane.io/v1beta1
          kind: SecurityGroup
          spec:
            forProvider:
              description: Security group for the db instance
              region: eu-west-2
              vpcId: testid
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.vpcId"
          toFieldPath: "spec.forProvider.vpcId"
      - name: securityGroupRule
        base:
          apiVersion: ec2.aws.crossplane.io/v1beta1
          kind: SecurityGroupRule
          spec:
            forProvider:
              description: Db ingress rule
              region: eu-west-2
              type: ingress
              fromPort: 5432
              toPort: 5432
              protocol: tcp
              cidrBlock: "10.106.0.0/23"
              securityGroupIdSelector:
                matchControllerRef: true
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.vpcCidr"
          toFieldPath: "spec.forProvider.cidrBlock"                          
      - name: dbCluster
        base:
          apiVersion: rds.aws.crossplane.io/v1alpha1
          kind: DBCluster
          spec:
            forProvider:
              allowMajorVersionUpgrade: false
              applyImmediately: false
              autoMinorVersionUpgrade: false
              backupRetentionPeriod: 1
              preferredBackupWindow: 07:00-09:00
              region: eu-west-2
              dbSubnetGroupNameSelector:
                matchControllerRef: true
              vpcSecurityGroupIDSelector:
                matchControllerRef: true
              masterUsername: masteruser
              databaseName: testdb
              engine: postgres
              skipFinalSnapshot: true
              publiclyAccessible: false
              allocatedStorage: 200
              storageType: io1
              iops: 4000              
              masterUserPasswordSecretRef:
                key: password
                name: secretName
            providerConfigRef:
              name: crossplane-provider-config
            writeConnectionSecretToRef:
              namespace: dbnamespace
              name: dbsecret

        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.dbClusterInstanceClass
          transforms:
          - type: map
            map:
              small: db.m5d.large
              medium: db.m5d.2xlarge
              large: db.m5d.8xlarge
        - fromFieldPath: spec.parameters.username
          toFieldPath: spec.forProvider.masterUsername
        - fromFieldPath: spec.parameters.dbName
          toFieldPath: spec.forProvider.databaseName
        - fromFieldPath: spec.parameters.engineVersion
          toFieldPath: spec.forProvider.engineVersion
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
        - fromFieldPath: spec.parameters.storageType
          toFieldPath: spec.forProvider.storageType
        - fromFieldPath: spec.parameters.storageIops
          toFieldPath: spec.forProvider.iops
        - fromFieldPath: spec.parameters.backupRetentionPeriod
          toFieldPath: spec.forProvider.backupRetentionPeriod                               
        - fromFieldPath: spec.parameters.preferredBackupWindow
          toFieldPath: spec.forProvider.preferredBackupWindow
        - fromFieldPath: spec.parameters.allowMajorVersionUpgrade
          toFieldPath: spec.forProvider.allowMajorVersionUpgrade
        - fromFieldPath: spec.parameters.autoMinorVersionUpgrade
          toFieldPath: spec.forProvider.autoMinorVersionUpgrade
        - fromFieldPath: spec.parameters.applyImmediately
          toFieldPath: spec.forProvider.applyImmediately      
        - fromFieldPath: spec.parameters.passwordSecret.name
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.name
        - fromFieldPath: spec.parameters.passwordSecret.key
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.key
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.namespace
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.dbName
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-connection-secret'              