#setup auth engine for dynamic secret generator using vault config op
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-dynamic-secret-vault
  namespace: ${ARGOCD_ENV_external_dns_namespace}
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-dynamic-secret-vault-token
  namespace: ${ARGOCD_ENV_external_dns_namespace}
  annotations:
    kubernetes.io/service-account.name: dns-dynamic-secret-vault
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ext-dns-dynamic-secret-vault-tokenreview-binding
  namespace: ${ARGOCD_ENV_external_dns_namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: dns-dynamic-secret-vault
    namespace: ${ARGOCD_ENV_external_dns_namespace}
---
#setup auth engine for dynamic secret generator using vault config op
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-dynamic-secret-vault
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-dynamic-secret-vault-token
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
  annotations:
    kubernetes.io/service-account.name: dns-dynamic-secret-vault
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-man-dynamic-secret-vault-tokenreview-binding
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: dns-dynamic-secret-vault
    namespace: ${ARGOCD_ENV_cert_manager_namespace}

---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: dns-dynamic-secret-vault
spec:
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  path: k8s-dns-auth
  tokenTTL: 3600
  policies:
    - cloudprovider-creds
  targetServiceAccounts:
    - dns-dynamic-secret-vault
  targetNamespaces:
    targetNamespaces:
      - ${ARGOCD_ENV_external_dns_namespace}
      - ${ARGOCD_ENV_cert_manager_namespace}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: cloudprovider-creds
spec:
  authentication:
    path: ${ARGOCD_ENV_vault_k8s_admin_auth_path}
    role: ${ARGOCD_ENV_vault_k8s_admin_role_name}
    serviceAccount:
      name: default
  policy: |
    # Configure sudo on cloud provider secrets
    path "cc-cloud-provider/creds/*" {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }
  type: acl
---
#this is external secret object, we are using k8s auth with custom k8s engine/role to authenticate the dynamic secret generator
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "cc-cloud-provider-external-dns"
  namespace: ${ARGOCD_ENV_external_dns_namespace}
spec:
  path: "cc-cloud-provider/creds/dns-access"
  provider:
    server: "http://vault-active.${ARGOCD_ENV_vault_namespace}.svc.cluster.local:8200"
    auth:
      kubernetes:
        mountPath: k8s-dns-auth
        role: dns-dynamic-secret-vault
        serviceAccountRef:
          name: "dns-dynamic-secret-vault"
          namespace: ${ARGOCD_ENV_external_dns_namespace}
        secretRef:
          name: "dns-dynamic-secret-vault-token"
          key: "token"
          namespace: ${ARGOCD_ENV_external_dns_namespace}
---
#create external secrets using vault dynamic sec generator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_external_dns_credentials_secret}"
  namespace: ${ARGOCD_ENV_external_dns_namespace}
spec:
  refreshInterval: "768h"
  target:
    name: ${ARGOCD_ENV_external_dns_credentials_secret}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: "cc-cloud-provider-external-dns"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "cc-cloud-provider-cert-manager"
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
spec:
  path: "cc-cloud-provider/creds/dns-access"
  provider:
    server: "http://vault-active.${ARGOCD_ENV_vault_namespace}.svc.cluster.local:8200"
    auth:
      kubernetes:
        mountPath: k8s-dns-auth
        role: dns-dynamic-secret-vault
        serviceAccountRef:
          name: "dns-dynamic-secret-vault"
          namespace: ${ARGOCD_ENV_cert_manager_namespace}
        secretRef:
          name: "dns-dynamic-secret-vault-token"
          key: "token"
          namespace: ${ARGOCD_ENV_cert_manager_namespace}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_certmanager_credentials_secret}"
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
spec:
  refreshInterval: "768h"
  target:
    name: ${ARGOCD_ENV_certmanager_credentials_secret}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: "cc-cloud-provider-cert-manager"
