---
#create external secrets using vault dynamic sec generator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_external_dns_credentials_secret}"
  namespace: ${ARGOCD_ENV_external_dns_namespace}
  labels:
    reloader: enabled
spec:
  refreshInterval: "45m"
  target:
    name: ${ARGOCD_ENV_external_dns_credentials_secret}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: "cc-cloud-provider-external-dns"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${ARGOCD_ENV_cert_manager_credentials_secret}"
  namespace: ${ARGOCD_ENV_cert_manager_namespace}
  labels:
    reloader: enabled
spec:
  refreshInterval: "45m"
  target:
    name: ${ARGOCD_ENV_cert_manager_credentials_secret}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: "cc-cloud-provider-cert-manager"
