apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - dns-external-secrets.yaml
  - istio-gateway-crs.yaml
  - lets-encrypt-cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    version: ${certmanager_helm_version}
    repo: https://charts.jetstack.io
    namespace: ${certmanager_namespace}
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true

  - name: external-dns
    releaseName: external-dns
    version: ${external_dns_helm_version}
    repo: https://charts.bitnami.com/bitnami
    valuesFile: ext-dns-values.yaml
    namespace: ${external_dns_namespace}
