apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ${ARGOCD_ENV_dbdeploy_name_prefix}-sc-secret
spec:
  # Watch for changes to the Namespace object.
  # Watching resources is an alpha feature and needs to be enabled with --enable-watches
  # in the provider to get this configuration working.
  # watch: true
  references:
  # Use patchesFrom to patch field from other k8s resource to this object
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: ${ARGOCD_ENV_db_secret}
      namespace: ${ARGOCD_ENV_namespace}
      fieldPath: data.password
    toFieldPath: data.password
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace:  ${ARGOCD_ENV_namespace}
      data:
        password: sample-value
  providerConfigRef:
    name: sc-kubernetes-provider