apiVersion: v1alpha1
sts-region: us-west-2 # TODO: do not hardcode. Understand what it is
discovery:
  # exportedTagsOnMetrics:
  #   AWS/EC2:
  #     - Name
    # ebs:
    #   - VolumeId

  jobs:
    - type: AWS/EC2
      regions: [us-west-2] # TODO: do not hardcode, understand what it is
      includeContextOnInfoMetrics: true
      searchTags:
        - key: Name
          value: 'Forem to Orbit bridge'
      dimensionNameRequirements:
        - InstanceId
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Maximum]
        - name: NetworkIn
          statistics: [Average, Sum]
        - name: NetworkOut
          statistics: [Average, Sum]
        - name: NetworkPacketsIn
          statistics: [Sum]
        - name: NetworkPacketsOut
          statistics: [Sum]
        - name: DiskReadBytes
          statistics: [Sum]
        - name: DiskWriteBytes
          statistics: [Sum]
        - name: DiskReadOps
          statistics: [Sum]
        - name: DiskWriteOps
          statistics: [Sum]
        - name: StatusCheckFailed
          statistics: [Sum]
        - name: StatusCheckFailed_Instance
          statistics: [Sum]
        - name: StatusCheckFailed_System
          statistics: [Sum]
