apiVersion: v1alpha1
sts-region: us-west-2 # TODO: do not hardcode. Understand what it is
discovery:
  jobs:
    - type: AWS/EC2
      regions: [us-west-2] # TODO: do not hardcode, understand what it is
      includeContextOnInfoMetrics: true
      searchTags:
        - key: App
          value: forem
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Maximum]
        - name: NetworkIn
          statistics: [Average]
