apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudwatch-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudwatch-exporter
    spec:
      containers:
      - name: cloudwatch-exporter
        image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.61.2
        args:
        - -config.file=/exporter/cloudwatch-exporter-config.yaml
        - -listen-address=:8080
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
        volumeMounts:
        - name: config-volume
          mountPath: /exporter
        - name: credentials-volume
          mountPath: /exporter/.aws/
      volumes:
      - name: config-volume
        configMap:
          name: cloudwatch-exporter-config
      - name: credentials-volume
        secret:
          secretName: cloudwatch-exporter-credentials
--- 
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter
  labels:
    app.kubernetes.io/name: cloudwatch-exporter  
spec:
  selector:
    app.kubernetes.io/name: cloudwatch-exporter
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  type: ClusterIP   
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudwatch-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudwatch-exporter
  endpoints:
  - port: http
    interval: 60s
    relabelings:
      - sourceLabels: [job]
        separator: ;
        regex: (.*)
        targetLabel: scrape_job # need to add this label because dashbords hardcode it
        replacement: "${1}"
        action: replace