apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              # image: grafana/grafana:${grafana_version} TODO: update later
              # env:
              #   - name: GF_SECURITY_ADMIN_USER
              #     valueFrom:
              #       secretKeyRef:
              #         key: ${admin_secret_user_key}
              #         name: ${admin_secret}
              #   - name: GF_SECURITY_ADMIN_PASSWORD
              #     valueFrom:
              #       secretKeyRef:
              #         key: ${admin_secret_pw_key}
              #         name: ${admin_secret}
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #       - matchExpressions:
          #         - key: 'workload-class.mojaloop.io/MONITORING'
          #           operator: In
          #           values: ['enabled']
  config:
    unified_alerting:
      enabled: "false"
    alerting:
      enabled: "true"
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: "Admin"      
    # server:
    #   domain: "${grafana_subdomain}"
    #   root_url: https://grafana.${grafana_subdomain}
    # auth.gitlab:
    #   enabled: "${enable_oidc}"
    #   allow_sign_up: "true"
    #   scopes: read_api
    #   auth_url: ${gitlab_server_url}/oauth/authorize
    #   token_url: ${gitlab_server_url}/oauth/token
    #   api_url: ${gitlab_server_url}/api/v4
    #   allowed_groups: ${groups}
    #   client_id: ${client_id}
    #   client_secret: ${client_secret}
    #   role_attribute_path: "is_admin && 'Admin' || 'Viewer'"