apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: grafana-mimir
  releaseName: central-monitoring
  version: 1.2.10
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesFile: values-mimir.yaml
# - name: mimir-distributed
#   releaseName: central-monitoring
#   version: 5.4.0
#   repo: https://grafana.github.io/helm-charts
#   valuesFile: values-mimir.yaml

# patches:
#   - target:
#       group: apps
#       version: v1
#       kind: StatefulSet
#       name: central-monitoring-grafana-mimir-compactor
#     patch: |-
#       - op: add
#         path: /spec/volumeClaimTemplates/-
#         value:
#           apiVersion: v1