# TODO: add proper templates
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-crs.yaml
helmCharts:
  - name: grafana-mimir
    releaseName: central-monitoring
    version: ${ARGOCD_ENV_grafana_mimir_helm_version}
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values-mimir.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
  - name: kube-prometheus
    releaseName: prom
    version: ${ARGOCD_ENV_kube_prometheus_helm_version}
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values-kube-prometheus.yaml
    namespace: ${ARGOCD_ENV_monitoring_namespace}
