minio:
  enabled: false

mimir:
  overrideConfiguration:
    limits:
      max_global_series_per_user: ${ARGOCD_ENV_mimir_max_global_series_per_user}
      ingestion_rate: ${ARGOCD_ENV_mimir_ingestion_rate}
      ingestion_burst_size: ${ARGOCD_ENV_mimir_ingestion_burst_size}

distributor:
  resourcesPreset: large

ingester:
  resourcesPreset: large