minio:
  enabled: false

mimir:
  blockStorage:
    backend: s3
    config:
      access_key_id: $${AWS_ACCESS_KEY_ID}
      secret_access_key: $${AWS_SECRET_ACCESS_KEY}
      bucket_name: $${BUCKET_NAME}
      endpoint: $${BUCKET_HOST}
      insecure: true
      bucket_lookup_type: path
  overrideConfiguration:
    limits:
      max_global_series_per_user: ${ARGOCD_ENV_mimir_max_global_series_per_user}
      ingestion_rate: ${ARGOCD_ENV_mimir_ingestion_rate}
      ingestion_burst_size: ${ARGOCD_ENV_mimir_ingestion_burst_size}
      compactor_blocks_retention_period: ${ARGOCD_ENV_mimir_retention_period}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    jobLabel: 'app.kubernetes.io/component'    
    relabelings:
    - sourceLabels: [job]
      separator: ;
      regex: (.*)
      targetLabel: job2
      replacement: ${1}
      action: replace


distributor:
  resourcesPreset: large

ingester:
  resourcesPreset: xlarge
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

querier:
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

query-frontend: 
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

compactor: 
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

storeGateway: 
  resourcesPreset: large
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}
