minio:
  enabled: true

mimir:
  blockStorage:
    backend: s3
    config: |
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}
      bucket_name: mimir
      endpoint: s3.us-east-1.amazonaws.com
      insecure: false
  overrideConfiguration:
    limits:
      max_global_series_per_user: ${ARGOCD_ENV_mimir_max_global_series_per_user}
      ingestion_rate: ${ARGOCD_ENV_mimir_ingestion_rate}
      ingestion_burst_size: ${ARGOCD_ENV_mimir_ingestion_burst_size}

distributor:
  resourcesPreset: large
  extraEnvVarsCM: mimir-bucket
  extraEnvVarsSecret: mimir-bucket

ingester:
  resourcesPreset: large