mimir:
  overrideConfiguration:
    limits:
      max_global_series_per_user: 1000000
      ingestion_rate: 200000
      ingestion_burst_size: 200000

distributor:
  resourcesPreset: large

ingester:
  resourcesPreset: large