alertmanager:
  enabled: false
  # externalConfig: true
  # configuration:
  #   name: alertmanager-config
  persistence:
    enabled: true
    storageClass: null
    size: 10Gi
prometheus:
  # persistence:
  #   enabled: true
  #   storageClass: longhorn
  #   size: 10Gi
  retention: 1d
  # setting these to prevent oom issue https://github.com/prometheus/prometheus/issues/6934#issuecomment-1099293120
  disableCompaction: false #this is the default anyway
  additionalArgs:
    - name: storage.tsdb.min-block-duration
      value: 30m
    - name: storage.tsdb.max-block-duration
      value: 30m
  externalLabels:
    cluster: control-center

  remoteWrite:
    - name: central-monitoring
      url: http://central-monitoring-grafana-mimir-gateway/api/v1/push
      headers:
        X-Scope-OrgID: infitx

kubelet:
  serviceMonitor:
    relabelings:
      # adds kubernetes_io_hostname label being used by k8s monitoring dashboard
      - sourceLabels: [node]
        separator: ;
        regex: (.*)
        targetLabel: kubernetes_io_hostname
        replacement: "${1}"
        action: replace

# commonLabels:
#   build: argocd
# commonAnnotations:
#   build: argocd

node-exporter:
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: nodename
  tolerations:
    - operator: "Exists"
blackboxExporter:
  enabled: false
