minio:
  enabled: false

mimir:
  blockStorage:
    backend: s3
    config:
      access_key_id: $${AWS_ACCESS_KEY_ID}
      secret_access_key: $${AWS_SECRET_ACCESS_KEY}
      bucket_name: $${BUCKET_NAME}
      endpoint: $${BUCKET_HOST}
      insecure: true
      bucket_lookup_type: path
  overrideConfiguration:
    limits:
      max_global_series_per_user: ${ARGOCD_ENV_mimir_max_global_series_per_user}
      ingestion_rate: ${ARGOCD_ENV_mimir_ingestion_rate}
      ingestion_burst_size: ${ARGOCD_ENV_mimir_ingestion_burst_size}
      compactor_blocks_retention_period: ${ARGOCD_ENV_mimir_retention_period}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    jobLabel: 'app.kubernetes.io/component'
    relabelings:
    - sourceLabels: [namespace,job]
      separator: /
      regex: (.*)
      targetLabel: job
      replacement: $${1}
      action: replace


# TODO: expose the resource config as configurable params
# resource preset guide: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl
distributor:
  replicaCount: 2
  resourcesPreset: medium

ingester:
  replicaCount: 3
  resourcesPreset: xlarge
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

querier:
  replicaCount: 2
  resourcesPreset: large
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

query-frontend: 
  replicaCount: 1
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

compactor: 
  replicaCount: 1
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}

storeGateway: 
  replicaCount: 2
  resourcesPreset: large
  extraEnvVarsCM: ${ARGOCD_ENV_mimir_bucket_name}
  extraEnvVarsSecret: ${ARGOCD_ENV_mimir_bucket_name}
