apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-ui
  # namespace: ${ARGOCD_ENV_gitlab_namespace}
  namespace: monitoring
spec:
  gateways:
    - ${ARGOCD_ENV_gitlab_istio_gateway_namespace}/${ARGOCD_ENV_gitlab_istio_wildcard_gateway_name}
  hosts:
    - "grafana.${ARGOCD_ENV_gitlab_dns_subdomain}"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana-service
            port:
              number: 3000