apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rook-ceph-namespace.yaml
  - rbac.yaml
  - external-secrets.yaml

helmCharts:
  - name: rook-ceph
    releaseName: rook-ceph
    version: ${ARGOCD_ENV_rook_ceph_helm_version}
    repo: https://charts.rook.io/release
    valuesFile: rook-ceph-values.yaml
    namespace: ${ARGOCD_ENV_storage_namespace}
    includeCRDs: true

  - name: rook-ceph-cluster
    releaseName: rook-ceph-cluster
    version: ${ARGOCD_ENV_rook_ceph_helm_version}
    repo: https://charts.rook.io/release
    valuesFile: ceph-external-values.yaml
    namespace: ${ARGOCD_ENV_storage_namespace}
    includeCRDs: true