apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-blockpool
  namespace: ${ARGOCD_ENV_rook_ceph_namespace}
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
    #targetSizeRatio: .5