apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: rook-ceph-cluster
    releaseName: rook-ceph-cluster
    version: ${ARGOCD_ENV_rook_ceph_helm_version}
    repo: https://charts.rook.io/release
    valuesFile: rook-ceph-cluster-values.yaml
    namespace: ${ARGOCD_ENV_rook_ceph_namespace}