---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-job-sa
  namespace: rook-ceph-external
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-job-role
  namespace: rook-ceph-external
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "namespaces"]
    verbs: ["create", "get", "list", "update", "patch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "get", "list", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-job-rolebinding
  namespace: rook-ceph-external
subjects:
  - kind: ServiceAccount
    name: ceph-job-sa
    namespace: rook-ceph-external
roleRef:
  kind: Role
  name: ceph-job-role
  apiGroup: rbac.authorization.k8s.io