apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - crossplane-providers.yaml
  - istio-gateway-crs.yaml
  - istio-external-ingress-gateway-values.yaml
  - istio-internal-ingress-gateway-values.yaml
  - lets-encrypt-cluster-issuer.yaml

helmCharts:
  - name: kubernetes-secret-generator
    releaseName: kubernetes-secret-generator
    version: ${kubernetes_secret_generator_helm_version}
    namespace: default
    repo: https://helm.mittwald.de
    includeCRDs: true

  - name: reflector
    releaseName: reflector
    version: ${reflector_helm_version}
    repo: https://emberstack.github.io/helm-charts
    namespace: reflector
    valuesInline:
      nameOverride: reflector

  - name: base
    releaseName: istio-base
    version: ${istio_helm_version}
    repo: https://istio-release.storage.googleapis.com/charts
    valuesFile: istio-base-values.yaml
    namespace: ${istio_namespace}
    includeCRDs: true

  - name: istiod
    releaseName: istiod
    version: ${istio_helm_version}
    repo: https://istio-release.storage.googleapis.com/charts
    valuesFile: istio-istiod-values.yaml
    namespace: ${istio_namespace}

  - name: cert-manager
    releaseName: cert-manager
    version: ${certmanager_helm_version}
    repo: https://charts.jetstack.io
    namespace: ${certmanager_namespace}
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true

  - name: external-dns
    releaseName: external-dns
    version: ${external_dns_helm_version}
    repo: https://charts.bitnami.com/bitnami
    valuesFile: ext-dns-values.yaml
    namespace: ${external_dns_namespace}

  - name: crossplane
    releaseName: crossplane
    version: ${crossplane_helm_version}
    repo: https://charts.crossplane.io/stable
    namespace: ${crossplane_namespace}
    includeCRDs: true
    valuesInline:
      args:
        - --${crossplane_debug}
