apiVersion: v1
kind: Service
metadata:
  name: rook-rgw-external
  namespace: ${ARGOCD_ENV_rook_ceph_namespace}
  annotations:
    metallb.universe.tf/address-pool: production
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: ceph-objectstore
spec:
  ports:
    - name: rgw
      port: 80 # service port mentioned in object store crd
      protocol: TCP
      targetPort: 8080
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: ceph-objectstore
  sessionAffinity: None
  type: LoadBalancer
  #type: NodePort
