#role is here since is specific to dns policy, this uses vault xplane provider for auth to create, similar to secretbackend CR
apiVersion: aws.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  name: cc-cloud-provider-dns-access

spec:
  providerConfigRef:
    name: vault-provider-config
  forProvider:
    backend: cc-cloud-provider
    credentialType: iam_user
    # name in vault will be route53-access
    name: dns-access
    policyArns:
      - ${ARGOCD_ENV_ext_dns_cloud_policy}
---

