apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: ${ARGOCD_ENV_monitoring_namespace}
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:${ARGOCD_ENV_grafana_image_version}
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: ${ARGOCD_ENV_grafana_admin_secret_user_key}
                      name: ${ARGOCD_ENV_grafana_admin_secret}
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${ARGOCD_ENV_grafana_admin_secret_pw_key}
                      name: ${ARGOCD_ENV_grafana_admin_secret}
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #       - matchExpressions:
          #         - key: 'workload-class.mojaloop.io/MONITORING'
          #           operator: In
          #           values: ['enabled']
  config:
    feature_toggles:
      ssoSettingsApi: true
    unified_alerting:
      enabled: "false"
    alerting:
      enabled: "true"
    auth.anonymous:
      enabled: "true"
      org_name: "Main Org."
      org_role: "Admin"
    server:
      domain: "${ARGOCD_ENV_grafana_dns_subdomain}"
      root_url: https://grafana.${ARGOCD_ENV_grafana_dns_subdomain}
