apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-post-config
  namespace: {{ vault_namespace }}
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
    - filename: zitadel-admin-sa.json
      source: Secret
      secretRef:
        namespace: {{ zitadel_namespace }}
        name: zitadel-admin-sa
        key: zitadel-admin-sa.json
    - filename: terraform.tfvars.json
      source: Secret
      secretRef:
        namespace: {{ vault_namespace }}
        name: {{ vault_keys_secret }}
        key: vault-keys.json
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-vault-post-config"
          namespace         = "{{ crossplane_namespace }}"
          in_cluster_config = true
        }
        required_providers {
          vault = "{{ vault_tf_provider_version }}"
          zitadel = {
            source = "zitadel/zitadel"
            version = "{{ zitadel_tf_provider_version }}"
          }
        }
      }
      variable "root_token" {
        type = string
      }
      provider "vault" {
        address = "https://vault.{{ dns_public_subdomain }}"
        token   = var.root_token
      }
      provider "zitadel" {
          jwt_profile_file = "${path.module}/zitadel-admin-sa.json"
          domain = "zitadel.{{ dns_public_subdomain }}"
      }
---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: vault-post-config
  namespace: {{ vault_namespace }}
spec:
  forProvider:
    # Use any module source supported by terraform init -from-module.
    source: Remote
    module: git::https://github.com/mojaloop/iac-modules.git//terraform/config-params/ccnew-config/vault?ref={{ vault_terraform_modules_tag }}
    # Variables can be specified inline as a list of key-value pairs or as an json object, or loaded from a ConfigMap or Secret.
    vars:
      - key: zitadel_fqdn
        value: zitadel.{{ dns_public_subdomain }}
      - key: vault_fqdn
        value: vault.{{ dns_public_subdomain }}
      - key: admin_rbac_group
        value: {{ vault_rbac_admin_group }}
      - key: oidc_provider_group_claim_prefix
        value: {{ zitadel_grant_prefix }}

  # All Terraform outputs are written to the connection secret.
  providerConfigRef:
    name: vault-post-config
  writeConnectionSecretToRef:
    namespace: {{ vault_namespace }}
    name: vault-post-config-tf-output