apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/argocd-helm.yaml
  - ../../../base/rook-ceph.yaml
  - ../../../base/external-secrets.yaml
  - ../../../base/reflector.yaml
  - ../../../base/crossplane.yaml
  - ../../../base/kubernetes-secret-generator.yaml
  - ../../../base/utils-post-config.yaml
  - ../../../base/istio.yaml
  - ../../../base/cert-manager.yaml
