apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.1.5

      helm:
        valuesObject:
          fullnameOverride: argocd
          applicationSet:
            enabled: false
          notifications:
            enabled: false
          dex:
            enabled: false
          configs:
            cm:
              kustomize.buildOptions: "--load-restrictor LoadRestrictionsNone"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
