apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "${ARGOCD_ENV_ceph_osd_volumes_storage_class}-csi"
provisioner: ebs.csi.aws.com
parameters:
  type: ${ARGOCD_ENV_ceph_osd_volumes_storage_class}
  fsType: ext4
  #iops: "3000"
  #throughput: "125"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer