apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volumes-storageclass.yaml

helmCharts:
  - name: aws-ebs-csi-driver
    releaseName: aws-ebs-csi-driver
    repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    namespace: kube-system

  - name: rook-ceph-cluster
    releaseName: rook-ceph-cluster
    version: ${ARGOCD_ENV_rook_ceph_helm_version}
    repo: https://charts.rook.io/release
    valuesFile: rook-ceph-cluster-values.yaml
    namespace: ${ARGOCD_ENV_rook_ceph_namespace}