name: Pull Request

on:
  workflow_call:
    inputs:
      CROSSPLANE_PACKAGES_DIR:
        required: true
        type: string

      CROSSPLANE_REGISTRY_URL:
        required: true
        type: string

      SUBPATH:
        required: true
        type: string

      NEXT_VERSION:
        required: true
        type: string

    secrets:
      REGISTRY_USERNAME:
        description: "Username for container registry to login"
        required: true

      REGISTRY_PASSWORD:
        description: "Password for container registry to login"
        required: true

jobs:
  # Build crossplane package
  build-xpackage-xpkg:
    name: Build Crossplane Composites
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.CROSSPLANE_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setup the Crossplane CLI
        run: "curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"

      - name: Prepare for packaging
        working-directory: ${{ inputs.CROSSPLANE_PACKAGES_DIR }}
        run: |
          echo "Preparing package for ${{ inputs.SUBPATH }}"
          make all PACKAGE_NAME=${{ inputs.SUBPATH }}

      - name: Build Package
        working-directory: ${{ inputs.CROSSPLANE_PACKAGES_DIR }}
        run: |
          echo "Building package for ${{ inputs.SUBPATH }}"
          # Create package directory if it doesn't exist
          mkdir -p ${{ inputs.SUBPATH }}/package
          ../crossplane xpkg build --package-root=${{ inputs.SUBPATH }}/configuration -o ${{ inputs.SUBPATH }}/package/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.xpkg

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.SUBPATH }}-package
          path: ${{ inputs.CROSSPLANE_PACKAGES_DIR }}/${{ inputs.SUBPATH }}/package/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.xpkg
          if-no-files-found: error
          retention-days: 1

  # publish crossplane package
  push-xPackage-xpkg:
    name: Push Crossplane package
    runs-on: ubuntu-latest
    needs:
      - build-xpackage-xpkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.SUBPATH }}-package
          path: ./artifacts

      - name: Setup the Crossplane CLI
        run: "curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.CROSSPLANE_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Package to registry
        run: |
          echo "Push package to registry"
          ./crossplane --verbose xpkg push -f ./artifacts/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.xpkg ${{ inputs.CROSSPLANE_REGISTRY_URL }}/${{ inputs.SUBPATH }}:${{ inputs.NEXT_VERSION }}
