name: Pull Request

on:
  workflow_call:
    inputs:
      CROSSPLANE_PACKAGES_DIR:
        required: true
        type: string

      CROSSPLANE_REGISTRY_URL:
        required: true
        type: string

      SUBPATH:
        required: true
        type: string

      NEXT_VERSION:
        required: true
        type: string

    secrets:
      REGISTRY_USERNAME:
        description: "Username for container registry to login"
        required: true

      REGISTRY_PASSWORD:
        description: "Password for container registry to login"
        required: true

jobs:
  # Build crossplane package
  build-xpackage-xpkg:
    name: Build Crossplane Composites
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.CROSSPLANE_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setup the Crossplane CLI
        run: "curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"

      - name: Prepare for package build
        run: |
          echo "PLACEHOLDER: Preparing for package build"
          echo "Working with package in ${{ inputs.CROSSPLANE_PACKAGES_DIR }}/${{ inputs.SUBPATH }}"
          # TODO: Add your preparation commands here

      - name: Build Package
        run: |
          echo "PLACEHOLDER: Building Crossplane package"
          # TODO: Add your package build commands here
          # Create a placeholder file for artifact for testing
          mkdir -p artifacts
          echo "Placeholder package content" > artifacts/crossplane-package.xpkg

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.SUBPATH }}-package
          path: artifacts/crossplane-package.xpkg
          if-no-files-found: error
          retention-days: 1

  # publish crossplane package
  push-xPackage-xpkg:
    name: Push Crossplane package
    runs-on: ubuntu-latest
    needs:
      - build-xpackage-xpkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.SUBPATH }}-package
          path: ./artifacts

      - name: Setup the Crossplane CLI
        run: "curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.CROSSPLANE_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Package to registry
        run: |
          echo "PLACEHOLDER: Pushing package to registry"
          echo "Would push artifact to ${{ inputs.CROSSPLANE_REGISTRY_URL }}/${{ inputs.SUBPATH }}:${{ inputs.NEXT_VERSION }}"
          # TODO: Add your push commands here
