apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nexus-ui
  namespace: ${ARGOCD_ENV_nexus_namespace} 
spec:
  gateways:
  - istio-ingress-int/internal-wildcard-gateway
  hosts:
    - 'nexus.int.devinfra.devbaremetal.moja-onprem.net'
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nexus-app-nexus3
            port:
              number: 80      
---              
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nexus-server-dtrl
spec:
  host: nexus-server
  trafficPolicy:
    tls:
      mode: SIMPLE                